### PR TITLE
fix some part of the decompress issue seen with #7

### PR DESCRIPTION
**Pull request by chcg**
fix some part of the decompress issue seen with #7
- wrong dir detection in zip as seen in zip of http://download.emmet.io/npp/emmet-npp.zip
- issue with CreateDirectoryA() which just creates one dir sublevel, but not recursively as seen in zip of https://bitbucket.org/ViRuSTriNiTy/nppbookmarkmanager/downloads/NppBookmarkManager_0_1_0_97_Unicode.zip
- unsure if also all zero file size issues are already fixed by this commit

### CODE REVIEW

**Comment by dinkumoil** [comment]
@chcg 

The plugins _Snippets_ and _BookmarkManager_ have unzip issues with _GUP.exe_ v5.0.4 according to [this](https://github.com/notepad-plus-plus/nppPluginList/issues/24) list. I have tested these plugins with a patched version of _GUP.exe_ that included your code.

### Results
#### _Snippets_

The ZIP file of _Snippets_ gets unzipped **correctly** now. Its directory structure is:

````Z
|   NppSnippets.dll
|
\---NppSnippets
        Languages.sql
        NppSnippets.sql
        Template.sqlite
````

With **unpatched** _GUP.exe_ v5.0.4 the file _Languages.sql_ had a length of 0 bytes after unzipping.


#### _BookmarkManager_

The ZIP file of _BookmarkManager_ can be unzipped now but one file has a length of 0 bytes . Its directory structure is:

````Z
|   NppBookmarkManager.dll
|
+---images
|   \---NppBookmarkManager
|       \---Marker
|               1.png
|               2.png
|               3.png
|               4.png
|               5.png
|               6.png
|               7.png
|               8.png
|               9.png
|
\---NppBookmarkManager
        License.txt
        README.md
````

Even with **patched** _GUP.exe_ v5.0.4 the file _License.txt_ has a length of 0 bytes.


### Final Notes

Even if these plugin ZIP files get unzipped correctly they have issues to find their companion files. The directories _NppSnippets_ and _images_ have to be moved to the old _plugins_ directory under the Notepad++ installation directory

**Comment by donho** [comment]
@chcg does this PR solve all the decompression issues we've found so far?

**Comment by dinkumoil** [comment]
@donho 

According to my test results - no. See results for _BookmarkManager_ plugin.

**Comment by chcg** [comment]
@dinkumoil 
That are also my observations, not all issues are fixed by this, but a first step forward.
@donho 
I case you want to move away from the current zip code you may want to use the one from PM for quite some time without problems based on zlib 1.2.11 (https://github.com/madler/zlib/releases/tag/v1.2.11). 
I would avoid switching from zip format to just 7z as we would loose again multiple plugins not maintained actively any more.

**Comment by donho** [comment]
@chcg I believe the unzip bug in WinGup has been fixed (no more zero length unzipped file) :
https://notepad-plus-plus.org/temp/GUP.zip

Could you confirm me if it’s fixed?

**Comment by donho** [comment]
@dinkumoil `BookmarkManager` cannot be find in the current plugin list.
Could you provid me the link to download it?

**Comment by dinkumoil** [comment]
@donho 

You can pick the download link from the command line I provided in my comment above.

Furthermore there is the [list of problematic plugins](https://github.com/notepad-plus-plus/nppPluginList/issues/24) created by @chcg.

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/wingup/commit/a4f12fd8cd0ca6eb6e44594b08ef6c9e2665a72e

**Pull request closed without merging**
